
import Link from "next/link";
import { comicNeue } from "./fonts";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${comicNeue.className}`}>
<header className="flex p-8 justify-end gap-8">
  <Link href="/">
  Home
  </Link>
  <Link href="/contact">
  contact
  </Link>
  <Link href="/about">
  about
  </Link>
</header>
        {children}
<footer>
  footer
</footer>
        </body>
    </html>
  );
}
